services:
  dev_db:
    image: postgres:15
    container_name: fire_sale_dev
    environment:
      - POSTGRES_USER=fire_sale
      - POSTGRES_PASSWORD=fire_sale
      - POSTGRES_DB=fire_sale_dev
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./priv/support/create_test_db.sql:/docker-entrypoint-initdb.d/1-schema.sql
